sudo: false

# http://docs.travis-ci.com/user/languages/cpp/
# start from https://github.com/rubinius/rubinius/blob/master/.travis.yml

language: cpp

compiler:
  - clang
  - gcc

# http://stackoverflow.com/a/30925448/1047788
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# http://docs.travis-ci.com/user/apt/
# https://github.com/mavam/vast/blob/master/.travis.prepare
# or just get gcc-multilib and g++-multilib and be done with it
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: 
      - gcc-4.8
      - g++-4.8
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - gcc-multilib
      - g++-multilib
      - clang
      #- libc6-dev-i386 #  missing header file 'bits/predefs.h'
      #- linux-libc-dev-i386 # this does NOT fix asm/errno.h: No such file or directory
      # - some other bunch of -i386 crap
# https://blog.lukaspradel.com/continuous-integration-for-cmake-projects-using-travis-ci/  
before_script:
  - mkdir cmakebuild
  - cd cmakebuild
  - cmake ..

script:
  - make && cd .. && cmakebuild/strongtalk-test
 
os:
  - linux

matrix:
  allow_failures:
    - compiler: clang